<a href="https://colab.research.google.com/github/NITINGORYAN/Python/blob/main/numpy_and_pandas_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
my_list=[1,2,3,4,5,6]

In [ ]:
type(my_list)

list

In [ ]:
arr=np.array(my_list)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
print(arr)

[1 2 3 4 5 6]


In [ ]:
my_list1=[7,2,3,4,5,6]
my_list2=[8,2,3,4,5,6]
my_list3=[9,2,3,4,5,6]

In [ ]:
arr_new=np.array([my_list1,my_list2,my_list3])

In [ ]:
print(arr_new)

[[7 2 3 4 5 6]
 [8 2 3 4 5 6]
 [9 2 3 4 5 6]]


In [ ]:
arr_new.shape

(3, 6)

In [ ]:
arr_new.reshape(6,3)

array([[7, 2, 3],
       [4, 5, 6],
       [8, 2, 3],
       [4, 5, 6],
       [9, 2, 3],
       [4, 5, 6]])

In [ ]:
# create random number
a=np.arange(0,25,5)

In [ ]:
print(a)

[ 0  5 10 15 20]


np.linspace(1,5,100)  

In [ ]:
np.random.rand(5,6)

array([[0.22346226, 0.42594406, 0.27065367, 0.55652428, 0.45111501,
        0.05464032],
       [0.49053907, 0.91877432, 0.92486605, 0.57503157, 0.72124973,
        0.38680838],
       [0.76675282, 0.05602869, 0.79394321, 0.12942092, 0.22849099,
        0.11790099],
       [0.44830835, 0.58390274, 0.41258752, 0.30330073, 0.00654718,
        0.43002723],
       [0.56060355, 0.68932831, 0.75082889, 0.87815771, 0.77042359,
        0.00424055]])

In [ ]:
np.random.randint(1,20,) # random integer display between 1 to 20

6

In [ ]:
np.random.randint(1,10,size=(3,4,2))

array([[[7, 6],
        [5, 4],
        [7, 9],
        [6, 8]],

       [[5, 6],
        [8, 2],
        [6, 1],
        [3, 4]],

       [[4, 6],
        [3, 1],
        [7, 5],
        [8, 9]]])

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("/content/tips.csv") # import data at pandas

In [ ]:
data.head() # by default display first 5 rows

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
data.tail() #Bydefault display last 5 rows

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
data.tail(15) #display last 15 rows

total_bill   tip     sex smoker   day    time  size
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
data.info() #information about dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB






**create a dummy dataset**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
my_data=pd.DataFrame(np.arange(1,21).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['col1','col2','col3','col4'])

In [ ]:
print(my_data)

      col1  col2  col3  col4
row1     1     2     3     4
row2     5     6     7     8
row3     9    10    11    12
row4    13    14    15    16
row5    17    18    19    20


In [ ]:
my_data_new=pd.DataFrame(np.arange(1,21).reshape(5,4))

In [ ]:
print(my_data_new)

    0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20


In [ ]:
my_data.to_csv("my_data.csv") #download creating dataset at csv file
my_data.to_excel("my_data.xlsx") #download creating dataset at excel file